# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_BASE = "cejkat/miesib2020-hw"
LOGIN_NAME = "miesib"
LOGIN_PASSWORD = "miesib"

Vagrant.configure("2") do |config|
 config.vm.define "dnsserv" do |dnsserv|
    dnsserv.vbguest.auto_update = false  
    dnsserv.vm.box = BOX_BASE
    dnsserv.vm.hostname = "dnsserv"
    dnsserv.ssh.username = LOGIN_NAME
    dnsserv.ssh.password = LOGIN_PASSWORD
    dnsserv.vm.network "private_network", ip: "192.168.56.12"
    dnsserv.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "512"
      vb.name = "dnsserv"
    end # End of virtualbox vb

    # Shared folders
    if Vagrant::Util::Platform.windows? then
      # Configuration SPECIFIC for Windows 10 hosts
      config.vm.synced_folder "shared", "/home/miesib/shared",
      id: "miesib-root", owner: "miesib", group: "miesib",
      mount_options: ["dmode=775", "fmode=664"]
    else
      # Configuration for Unix/Linux hosts
      config.vm.synced_folder "shared", "/home/miesib/shared",
      mount_options: ["dmode=775", "fmode=664"]
    end # of shared folders
  
    dnsserv.vm.provision "shell", inline: <<-SHELL
        #install
        yum update -y
    SHELL
  end # End of provisioning

  config.vm.define "attacker" do |config|
    config.vm.box = BOX_BASE
    config.vm.hostname = "attacker"
    config.ssh.username = LOGIN_NAME 
    config.ssh.password = LOGIN_PASSWORD
    config.vbguest.auto_update = false  
  
    config.vm.network "private_network", ip: "192.168.56.11"

    # Shared folders
    if Vagrant::Util::Platform.windows? then
      # Configuration SPECIFIC for Windows 10 hosts
      config.vm.synced_folder "shared", "/home/miesib/shared",
      id: "miesib-root", owner: "miesib", group: "miesib",
      mount_options: ["dmode=775", "fmode=664"]
    else
      # Configuration for Unix/Linux hosts
      config.vm.synced_folder "shared", "/home/miesib/shared",
      mount_options: ["dmode=775", "fmode=664"]
    end # of shared folders
  
    config.vm.provider "virtualbox" do |vb|
      # Display the VirtualBox GUI when booting the machine
      vb.gui = false
    
      # Customize the amount of memory on the VM:
      vb.memory = "2048"
      vb.name = "attacker"
    end # End of virtualbox vb
  end # End of mitm config


  config.vm.define "victimServer" do |config|
    config.vm.box = BOX_BASE
    config.vm.hostname = "victimServer"
    config.ssh.username = LOGIN_NAME 
    config.ssh.password = LOGIN_PASSWORD
    config.vbguest.auto_update = false  
  
    config.vm.network "private_network", ip: "192.168.56.10"

    # Shared folders
    if Vagrant::Util::Platform.windows? then
      # Configuration SPECIFIC for Windows 10 hosts
      config.vm.synced_folder "shared", "/home/miesib/shared",
      id: "miesib-root", owner: "miesib", group: "miesib",
      mount_options: ["dmode=775", "fmode=664"]
    else
      # Configuration for Unix/Linux hosts
      config.vm.synced_folder "shared", "/home/miesib/shared",
      mount_options: ["dmode=775", "fmode=664"]
    end # of shared folders
  
    config.vm.provider "virtualbox" do |vb|
      # Display the VirtualBox GUI when booting the machine
      vb.gui = false
    
      # Customize the amount of memory on the VM:
      vb.memory = "512"
      vb.name = "victimServer"
    end # End of virtualbox vb
  end # End of victim config
end # End of Vagrantfile