# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_BASE = "cejkat/miesib2020-hw"
BOX_RAM = "2048"
LOGIN_NAME = "miesib"
LOGIN_PASSWORD = "miesib"

Vagrant.configure("2") do |config|

  config.vm.define "victim" do |config|
    config.vm.box = BOX_BASE
    config.vm.hostname = "victim"
    config.ssh.username = LOGIN_NAME 
    config.ssh.password = LOGIN_PASSWORD
  
    config.vm.network "private_network", ip: "192.168.56.10"
    # config.vm.box_check_update = true
    # config.vm.network "forwarded_port", guest: 80, host: 8080
    # config.vm.synced_folder "../data", "/vagrant_data"
  
    config.vm.provider "virtualbox" do |vb|
      # Display the VirtualBox GUI when booting the machine
      vb.gui = false
    
      # Customize the amount of memory on the VM:
      vb.memory = BOX_RAM
      vb.name = "victim"
    end # End of virtualbox vb
  end # End of victim config


  config.vm.define "mitm" do |config|
    config.vm.box = BOX_BASE
    config.vm.hostname = "mitm"
    config.ssh.username = LOGIN_NAME 
    config.ssh.password = LOGIN_PASSWORD
  
    config.vm.network "private_network", ip: "192.168.56.11"
    # config.vm.box_check_update = true
    # config.vm.network "forwarded_port", guest: 80, host: 8080
    # config.vm.synced_folder "../data", "/vagrant_data"

    # Shared folders
    if Vagrant::Util::Platform.windows? then
      # Configuration SPECIFIC for Windows 10 hosts
      config.vm.synced_folder "shared", "/home/miesib/shared",
      id: "miesib-root", owner: "miesib", group: "miesib",
      mount_options: ["dmode=775", "fmode=664"]
    else
      # Configuration for Unix/Linux hosts
      config.vm.synced_folder "shared", "/home/miesib/shared",
      mount_options: ["dmode=775", "fmode=664"]
    end # of shared folders
  
    config.vm.provider "virtualbox" do |vb|
      # Display the VirtualBox GUI when booting the machine
      vb.gui = false
    
      # Customize the amount of memory on the VM:
      vb.memory = BOX_RAM
      vb.name = "mitm"
    end # End of virtualbox vb
  end # End of mitm config


  config.vm.define "server" do |config|
    config.vm.box = BOX_BASE
    config.vm.hostname = "server"
    config.ssh.username = LOGIN_NAME 
    config.ssh.password = LOGIN_PASSWORD
  
    config.vm.network "private_network", ip: "192.168.56.12"
    # config.vm.box_check_update = true
    # config.vm.network "forwarded_port", guest: 80, host: 8080
    # config.vm.synced_folder "../data", "/vagrant_data"
  
    config.vm.provider "virtualbox" do |vb|
      # Display the VirtualBox GUI when booting the machine
      vb.gui = false
    
      # Customize the amount of memory on the VM:
      vb.memory = BOX_RAM
      vb.name = "server"
    end # End of virtualbox vb
  end # End of server config
end
  